In [48]:
import numpy as np
from scipy.optimize import minimize

#Example Problem
CAPACITY = [10000, 12000, 14000]
DEMAND = [9000, 6000, 6000, 13000]
COST = np.array([[5, 3.5, 4.2, 2.2],
                 [3.2, 2.6, 1.8, 4.8],
                 [2.5, 3.1, 3.3, 5.4]])
COST = COST.flatten()

x0 = [0]*12
bnds = tuple((0,14000) for x in x0)

#Set constraints
def con_la_capacity(x): return CAPACITY[0] - (x[0] + x[1] + x[2] + x[3])
def con_atl_capacity(x): return CAPACITY[1] - (x[4] + x[5] + x[6] + x[7])
def con_ny_capacity(x): return CAPACITY[2] - (x[8] + x[9] + x[10] + x[11])
def con_e_demand(x): return DEMAND[0] - (x[0] + x[4] + x[8])
def con_mw_demand(x): return DEMAND[1] - (x[1] + x[5] + x[9])
def con_s_demand(x): return DEMAND[2] - (x[2] + x[6] + x[10])
def con_w_demand(x): return DEMAND[3] - (x[3] + x[7] + x[11])

cons = [{'type': 'ineq', 'fun': con_la_capacity},
        {'type': 'ineq', 'fun': con_atl_capacity},
        {'type': 'ineq', 'fun': con_ny_capacity},
        {'type': 'eq', 'fun': con_e_demand},
        {'type': 'eq', 'fun': con_mw_demand},
        {'type': 'eq', 'fun': con_s_demand},
        {'type': 'eq', 'fun': con_w_demand}]

def total_cost(x):
    cost = sum([a*b for a,b in zip(x,COST)])
    return cost

res = minimize(total_cost, x0, method = 'SLSQP', constraints = cons, bounds = bnds)
min_cost = res.fun
solution1 = res.x.reshape(3,4)
solution1 = np.rint(solution1)

In [49]:
print(solution1, 'Minimum Cost: $', min_cost)

[[     0.      0.      0.  10000.]
 [     0.   3000.   6000.   3000.]
 [  9000.   3000.      0.      0.]] Minimum Cost: $ 86800.0


In [31]:
################ PROBLEM 2 ################

SALES_PRICE = [45, 40, 38, 36, 39, 34]*6
TAX_RATE = [0.3, 0.4, 0.2, 0.4, 0.35, 0.18]*6
PROD_COST = [8, 7, 6, 9, 7, 7]*6
DEMAND = [1000000, 2000000, 3000000, 4000000, 5000000, 6000000]
CAPACITY = [6000000, 6000000, 6000000, 6000000, 6000000, 6000000]
SHIP_COST = np.array([[3, 4, 5, 6, 7, 8], 
                      [5, 2, 6, 9, 10, 11], 
                      [4, 3, 1, 6, 8, 6],
                      [5, 5, 7, 2, 5, 5],
                      [6, 9, 6, 5, 3, 7],
                      [7, 7, 8, 9, 10, 4]])
SHIP_COST = SHIP_COST.flatten()

x0 = [0]*36
bnds = tuple((0,6000000) for x in x0)

#Set constraints
def con_capacity1(x): return CAPACITY[0] - (x[0] + x[1] + x[2] + x[3] + x[4] + x[5])
def con_capacity2(x): return CAPACITY[1] - (x[6] + x[7] + x[8] + x[9] + x[10] + x[11])
def con_capacity3(x): return CAPACITY[2] - (x[12] + x[13] + x[14] + x[15] + x[16] + x[17])
def con_capacity4(x): return CAPACITY[3] - (x[18] + x[19] + x[20] + x[21] + x[22] + x[23])
def con_capacity5(x): return CAPACITY[4] - (x[24] + x[25] + x[26] + x[27] + x[28] + x[29])
def con_capacity6(x): return CAPACITY[5] - (x[30] + x[31] + x[32] + x[33] + x[34] + x[35])
def con_demand1(x): return DEMAND[0] - (x[0] + x[6] + x[12] + x[18] + x[24] + x[30])
def con_demand2(x): return DEMAND[1] - (x[1] + x[7] + x[13] + x[19] + x[25] + x[31])
def con_demand3(x): return DEMAND[2] - (x[2] + x[8] + x[14] + x[20] + x[26] + x[32])
def con_demand4(x): return DEMAND[3] - (x[3] + x[9] + x[15] + x[21] + x[27] + x[33])
def con_demand5(x): return DEMAND[4] - (x[4] + x[10] + x[16] + x[22] + x[28] + x[34])
def con_demand6(x): return DEMAND[5] - (x[5] + x[11] + x[17] + x[23] + x[29] + x[35])

cons = [{'type': 'ineq', 'fun': con_capacity1},
        {'type': 'ineq', 'fun': con_capacity2},
        {'type': 'ineq', 'fun': con_capacity3},
        {'type': 'ineq', 'fun': con_capacity4},
        {'type': 'ineq', 'fun': con_capacity5},
        {'type': 'ineq', 'fun': con_capacity6},
        {'type': 'eq', 'fun': con_demand1},
        {'type': 'eq', 'fun': con_demand2},
        {'type': 'eq', 'fun': con_demand3},
        {'type': 'eq', 'fun': con_demand4},
        {'type': 'eq', 'fun': con_demand5},
        {'type': 'eq', 'fun': con_demand6}]

def profit(x):
    revenue = [a*b for a,b in zip(x,SALES_PRICE)]
    prodcosts = [a*b for a,b in zip(x,PROD_COST)] 
    shipcosts = [a*b for a,b in zip(x,SHIP_COST)]
    total_costs = [a+b for a,b in zip(prodcosts, shipcosts)]
    profit = [a-b for a,b in zip(revenue, total_costs)]
    taxes = [a*b for a,b in zip(profit, TAX_RATE)]
    aftertax_profit = sum(profit) - sum(taxes)
    aftertax_profit = aftertax_profit*-1 #to maximize
    return aftertax_profit

res = minimize(profit, x0, method = 'SLSQP', constraints = cons, bounds = bnds)
max_aftertax_profit = res.fun
solution2 = res.x.reshape(6,6).astype(int)

In [32]:
#PROBLEM 2 SOLUTION (assumes tax rate applied to profits, not revenues)
print(solution2, 'Max After-Tax Profit: $', max_aftertax_profit*-1)

[[ 428604  413462 1187670  546524  580435 1147994]
 [  43394  489346  461323   38657  305485       0]
 [ 342809  400640 1056172  737052  513409 1215257]
 [  61227  622076       0 1232919 1503322 1454170]
 [    117   51332  294832  924093 1714306  691882]
 [ 123846   23141       0  520751  383040 1490694]] Max After-Tax Profit: $ 369098881.212


In [15]:
################ PROBLEM 3 ################

CAPACITY = [70000, 70000, 70000]
DEMAND = [40000, 40000, 40000, 40000, 40000]
DISTANCE = np.array([[983, 0, 1205, 2112, 1390],
                     [1815, 1205, 0, 801, 1332],
                     [1539, 1390, 1332, 2757, 0]])
DISTANCE = DISTANCE.flatten()

x0 = [0]*15
bnds = tuple((0,40000) for x in x0)

#Set constraints
def con_capacity_chi(x): return CAPACITY[0] - (x[0] + x[1] + x[2] + x[3] + x[4])
def con_capacity_dal(x): return CAPACITY[1] - (x[5] + x[6] + x[7] + x[8] + x[9])
def con_capacity_mia(x): return CAPACITY[2] - (x[10] + x[11] + x[12] + x[13] + x[14])
def con_demand_bos(x): return DEMAND[0] - (x[0] + x[5] + x[10])
def con_demand_chi(x): return DEMAND[1] - (x[1] + x[6] + x[11])
def con_demand_dal(x): return DEMAND[2] - (x[2] + x[7] + x[12])
def con_demand_la(x): return DEMAND[3] - (x[3] + x[8] + x[13])
def con_demand_mia(x): return DEMAND[4] - (x[4] + x[9] + x[14])

cons = [{'type': 'ineq', 'fun': con_capacity_chi},
        {'type': 'ineq', 'fun': con_capacity_dal},
        {'type': 'ineq', 'fun': con_capacity_mia},
        {'type': 'eq', 'fun': con_demand_bos},
        {'type': 'eq', 'fun': con_demand_chi},
        {'type': 'eq', 'fun': con_demand_dal},
        {'type': 'eq', 'fun': con_demand_la},
        {'type': 'eq', 'fun': con_demand_mia}]

def total_cost(x):
    dist = DISTANCE/100 #convert to 100s of miles
    x = x/1000 #convert to 1000s of kwh
    cost = (sum([a*b for a,b in zip(x,dist)]))*4
    return cost

res = minimize(total_cost, x0, method = 'SLSQP', constraints = cons, bounds = bnds)
min_cost = res.fun
solution3 = res.x.reshape(3,5)
solution3 = np.rint(solution3)

In [16]:
print(solution3, 'Minimum Cost: $', min_cost)

[[ 30000.  40000.      0.      0.      0.]
 [     0.      0.  30000.  40000.      0.]
 [ 10000.      0.  10000.      0.  40000.]] Minimum Cost: $ 3609.6000003


In [38]:
################ PROBLEM 4 ################

#[north, central south]
CAPACITY = [120, 120, 40]
DEMAND = [100, 100, 100] #in billions of gallons
SHIP_COST = np.array([[5000, 7000, 10000],
                     [7000, 5000, 6000],
                     [10000, 6000, 5000]])
SHIP_COST = SHIP_COST.flatten()
SHORT_COST = [6000, 5500, 9000]

x0 = [0]*9
bnds = tuple((0,100) for x in x0)

#Set constraints
def con_capacity_n(x): return CAPACITY[0] - (x[0] + x[1] + x[2])
def con_capacity_c(x): return CAPACITY[1] - (x[3] + x[4] + x[5])
def con_capacity_s(x): return CAPACITY[2] - (x[6] + x[7] + x[8])
def con_capacity_all(x): return sum(CAPACITY) - sum(x) #to use up all capacity
def con_demand_n(x): return DEMAND[0] - (x[0] + x[3] + x[6])
def con_demand_c(x): return DEMAND[1] - (x[1] + x[4] + x[7])
def con_demand_s(x): return DEMAND[2] - (x[2] + x[5] + x[8])

cons = [{'type': 'ineq', 'fun': con_capacity_n},
        {'type': 'ineq', 'fun': con_capacity_c},
        {'type': 'ineq', 'fun': con_capacity_s},
        {'type': 'eq', 'fun': con_capacity_all},
        {'type': 'ineq', 'fun': con_demand_n},
        {'type': 'ineq', 'fun': con_demand_c},
        {'type': 'ineq', 'fun': con_demand_s},]

def total_cost(x):
    shippingCost = sum([a*b for a,b in zip(x,SHIP_COST)])
    
    nShort = DEMAND[0] - (x[0] + x[3] + x[6])
    cShort = DEMAND[1] - (x[1] + x[4] + x[7])
    sShort = DEMAND[2] - (x[2] + x[5] + x[8])
    shortageAmt = [nShort, cShort, sShort]
    shortageCost = sum([a*b for a,b in zip(shortageAmt, SHORT_COST)])
    
    cost = shippingCost + shortageCost
    return cost

res = minimize(total_cost, x0, method = 'SLSQP', constraints = cons, bounds = bnds)
min_cost = res.fun
solution4 = res.x.reshape(3,3)
solution4 = np.rint(solution4)

In [39]:
print(solution4, 'Minimum Cost: $', min_cost)

[[ 100.   20.    0.]
 [   0.   60.   60.]
 [   0.    0.   40.]] Minimum Cost: $ 1609999.94448
